### ISSUE TITLE
How to translation locale

### ISSUE THREAD

**Issue by allancmello** [wpkyoto/stripe-pwa-elements#33]
Hi,

Where can I find an example of how to translate card elements into my language? Title label, card, etc?
I saw that there is an i18n.ts file but when including "pt-BR" the component does not recognize the language, the Javascript does not accept.

**Comment by hideokamoto** [comment]
Hi @allancmello !
For now, the texts in the UI provided by this library are translated in i18next package based on this document:
https://github.com/wpkyoto/stripe-pwa-elements/blob/main/src/utils/i18n.ts
The elements that Stripe SDK(iOS / Android / and stripe.js) provided are translated by Stripe's code.

Therefore, if you want to translate into your language, you need to make a new Pull Request to update this file.

Best regards.

**Comment by allancmello** [comment]
Hi @hideokamoto 

I submitted a pull request with the changes requested on i18n.ts for the Brazilian Portuguese language code.

Thanks

**Comment by hideokamoto** [comment]
I merged your PR!
And published the new version.
https://github.com/wpkyoto/stripe-pwa-elements/releases/tag/v2.1.0

Please upgrade this package to 2.1.0.

**Comment by allancmello** [comment]
Thanks kamoto!
